### ISSUE TITLE
Homepage rework

### ISSUE THREAD

**Issue by giorgiagalbullicavazzini** [LucaBrivio183/deliveboo-frontend#19]
- [x] "Scelti per te" should be modified and should contain an info about what has been chosen for you
- [x] Insert a sort of jumbotron with a flamingo and the name and the slogan of the website
- [x] Typologies filters should be centered
- [x] Add to typologies a proper icon
- [x] After selecting a typology, the other ones (if not available as a proper combination) should become gray

**Comment by LucaBrivio183** [comment]
gj
